import os

DEBUG = False
TESTING = False

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI = os.environ.get('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_ECHO = False

SECRET_KEY = os.environ.get('SECRET_KEY')
CSRF_ENABLED = True
WTF_CSRF_ENABLED = CSRF_ENABLED

FLATPAGES_EXTENSION = '.html.md'
FLATPAGES_MARKDOWN_EXTENSIONS = []
